name: Publish to WinGet
on:
  release:
    types: [released]
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: Start-Sleep -Seconds 300 # 5 minutes
        shell: pwsh
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Jackett.Jackett
          token: ${{ secrets.WINGET }}
